-- -------------------------------------------------------------
-- 
-- File Name: /home/matt/OPV_TX_abraxas3d/create-even-and-odd-HDL/hdlsrc/opv_pluto_transmitter_HDL_coder_input/fpga_data_capture.vhd
-- Created: 2024-04-20 21:17:07
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: fpga_data_capture
-- Source Path: opv_modul_ip/fpga_data_capture
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY fpga_data_capture IS
  PORT( clk                               :   IN    std_logic;
        bo_bitstream                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        be_bitstream                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        clk_enable_1                      :   IN    std_logic  -- ufix1
        );
END fpga_data_capture;


ARCHITECTURE rtl OF fpga_data_capture IS

  -- Component Declarations
  COMPONENT FPGADataCapture
    PORT( clk                             :   IN    std_logic;
          bo_bitstream                    :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          be_bitstream                    :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          clk_enable                      :   IN    std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : FPGADataCapture
    USE ENTITY work.FPGADataCapture(rtl);

BEGIN
  u_data_capture : FPGADataCapture
    PORT MAP( clk => clk,
              bo_bitstream => bo_bitstream,  -- sfix16_En15
              be_bitstream => be_bitstream,  -- sfix16_En15
              clk_enable => clk_enable_1  -- ufix1
              );

END rtl;

